
USE DB_EMPRESA_SOFTWARE;

CREATE TABLE EMPRESA_CLIENTE(
ID_EMPRESA_CLIENTE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
CIF_EMPRESA NVARCHAR(30) NOT NULL UNIQUE,
NOMBRE_EMPRESA NVARCHAR(100) NOT NULL,
DIRECCION NVARCHAR(250) NOT NULL,
TELEFONO NVARCHAR(20) NOT NULL,
CODIGO_INTERNO INT ,
CREATED_AT DATETIME2 NOT NULL  CONSTRAINT DF_EMPRESA_CLIENTE_CREATED_AT  DEFAULT SYSDATETIME(),
UPDATED_AT DATETIME2 NOT NULL CONSTRAINT DF_EMPRESA_CLIENTE_UPDATED_AT  DEFAULT SYSDATETIME()
);

CREATE TABLE PROFESION(
ID_PROFESION INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
NOMBRE_PROFESION NVARCHAR(100) NOT NULL,
CREATED_AT DATETIME2 NOT NULL  CONSTRAINT DF_PROFESION_CREATED_AT  DEFAULT SYSDATETIME(),
UPDATED_AT DATETIME2 NOT NULL CONSTRAINT DF_PROFESION_UPDATED_AT  DEFAULT SYSDATETIME()

);
CREATE TABLE ESTADO_PROYECTO (
ID_ESTADO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
NOMBRE_ESTADO NVARCHAR(100) NOT NULL,
CREATED_AT DATETIME2 NOT NULL  CONSTRAINT DF_ESTADO_CREATED_AT  DEFAULT SYSDATETIME(),
UPDATED_AT DATETIME2 NOT NULL CONSTRAINT DF_ESTADO_UPDATED_AT  DEFAULT SYSDATETIME()
);

CREATE TABLE DEPARTAMENTO (
ID_DEPARTAMENTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
NOMBRE_DEPARTAMENTO  NVARCHAR(100) NOT NULL,
CREATED_AT DATETIME2 NOT NULL  CONSTRAINT DF_DEPARTAMENTO_CREATED_AT  DEFAULT SYSDATETIME(),
UPDATED_AT DATETIME2 NOT NULL CONSTRAINT DF_DEPARTAMENTO_UPDATED_AT  DEFAULT SYSDATETIME()
);

CREATE TABLE EMPLEADO (
ID_EMPLEADO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ID_PROFESION INT NOT NULL,
ID_DEPARTAMENTO INT NOT NULL,
ID_JEFE INT NULL,
DNI_EMPLEADO NVARCHAR(20) NOT NULL ,
NOMBRE_EMPLEADO NVARCHAR(100) NOT NULL,
APELLIDO_EMPLEADO NVARCHAR(100) NOT NULL,
CREATED_AT DATETIME2 NOT NULL  CONSTRAINT DF_EMPLEADO_CREATED_AT  DEFAULT SYSDATETIME(),
UPDATED_AT DATETIME2 NOT NULL CONSTRAINT DF_EMPLEADO_UPDATED_AT  DEFAULT SYSDATETIME(),

CONSTRAINT  FK_EMPLEADOS_PROFESION
FOREIGN KEY (ID_PROFESION)
REFERENCES PROFESION(ID_PROFESION),

CONSTRAINT FK_EMPLEADO_DEPARTAMENTO
FOREIGN KEY (ID_DEPARTAMENTO)
REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),

CONSTRAINT FK_EMPLEADO_JEFE FOREIGN KEY (ID_JEFE) REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE TARIFA (
ID_TARIFA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ID_PROFESION INT NOT NULL,
MONTO_HORA DECIMAL (10,2) NOT NULL,
CREATED_AT DATETIME2 NOT NULL  CONSTRAINT DF_TARIFA_CREATED_AT  DEFAULT SYSDATETIME(),
UPDATED_AT DATETIME2 NOT NULL CONSTRAINT DF_TARIFA_UPDATED_AT  DEFAULT SYSDATETIME(),

CONSTRAINT  FK_TARIFA_PROFESION 
FOREIGN KEY (ID_PROFESION)
REFERENCES PROFESION(ID_PROFESION)

);
CREATE TABLE PROYECTO (
ID_PROYECTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ID_EMPRESA_CLIENTE INT NOT NULL,
NOMBRE_PROYECTO NVARCHAR(100) NOT NULL,
FECHA_INICIO DATETIME NOT NULL,
ID_ESTADO INT  NOT NULL,
CREATED_AT DATETIME2 NOT NULL  CONSTRAINT DF_PROYECTO_CREATED_AT  DEFAULT SYSDATETIME(),
UPDATED_AT DATETIME2 NOT NULL CONSTRAINT DF_PROYECTO_UPDATED_AT  DEFAULT SYSDATETIME(),

CONSTRAINT FK_PROYECTO_EMPRESA_CLIENTE
FOREIGN KEY (ID_EMPRESA_CLIENTE)
REFERENCES EMPRESA_CLIENTE(ID_EMPRESA_CLIENTE),

CONSTRAINT FK_PROYECTOS_ESTADO
FOREIGN KEY (ID_ESTADO)
REFERENCES ESTADO_PROYECTO(ID_ESTADO)

);
CREATE TABLE DETALLE_PROYECTO (
ID_DETALLE_PROYECTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ID_EMPLEADO INT NOT NULL,
ID_PROYECTO INT NOT NULL,
ID_TARIFA INT NOT  NULL,
HORAS_TRABAJADAS DECIMAL(10,2) NOT NULL,
COSTO_HORA DECIMAL(10,2) NOT NULL,
FECHA_VIGENTE DATE NOT NULL,
CREATED_AT DATETIME2 NOT NULL  CONSTRAINT DF_DETALLE_PROYECTO_CREATED_AT  DEFAULT SYSDATETIME(),
UPDATED_AT DATETIME2 NOT NULL CONSTRAINT DF_DETALLE_PROYECTO_UPDATED_AT  DEFAULT SYSDATETIME(),

CONSTRAINT FK_DETALLE_PROYECTO_EMPLEADO
FOREIGN KEY (ID_EMPLEADO)
REFERENCES EMPLEADO(ID_EMPLEADO),

CONSTRAINT FK_DETALLE_PROYECTO_PROYECTO
FOREIGN KEY (ID_PROYECTO)
REFERENCES PROYECTO(ID_PROYECTO),

CONSTRAINT FK_DETALLE_PROYECTO_TARIFA
FOREIGN KEY (ID_TARIFA)
REFERENCES TARIFA(ID_TARIFA)

);