USE DB_EMPRESA_SOFTWARE;
GO

-- (VW_CONSOLIDADOPROYECTOS) CONSOLIDA LAS HORAS TRABAJADAS, COSTO TOTAL Y ESTADO ACTUAL POR PROYECTO.

CREATE VIEW VW_CONSOLIDADOPROYECTOS AS
SELECT 
    P.ID_PROYECTO AS CODIGO_PROYECTO,
    P.NOMBRE_PROYECTO AS PROYECTO,
    EC.NOMBRE_EMPRESA AS CLIENTE,
    EP.NOMBRE_ESTADO AS ESTADO,
    P.FECHA_INICIO AS FECHA_INICIO,
    ISNULL(SUM(DP.HORAS_TRABAJADAS), 0) AS TOTAL_HORAS_TRABAJADAS,
    -- CALCULAMOS EL COSTO TOTAL DEL PROYECTO MULTIPLICANDO HORAS POR COSTO DE HORA CONGELADO
    CAST(ISNULL(SUM(DP.HORAS_TRABAJADAS * DP.COSTO_HORA), 0) AS DECIMAL(12,2)) AS COSTO_TOTAL_ACUMULADO
FROM PROYECTO P
INNER JOIN EMPRESA_CLIENTE EC ON P.ID_EMPRESA_CLIENTE = EC.ID_EMPRESA_CLIENTE
INNER JOIN ESTADO_PROYECTO EP ON P.ID_ESTADO = EP.ID_ESTADO
LEFT JOIN DETALLE_PROYECTO DP ON P.ID_PROYECTO = DP.ID_PROYECTO
GROUP BY P.ID_PROYECTO, P.NOMBRE_PROYECTO, EC.NOMBRE_EMPRESA, EP.NOMBRE_ESTADO, P.FECHA_INICIO;
GO

---------------

--  (VW_ORGANIGRAMAEMPLEADOS) MUESTRA EL DEPARTAMENTO, PROFESIÓN Y EL NOMBRE DEL JEFE DIRECTO (SELF-JOIN)

CREATE VIEW VW_ORGANIGRAMAEMPLEADOS AS
SELECT 
    E.ID_EMPLEADO AS ID,
    E.DNI_EMPLEADO AS DNI,
    CONCAT(E.NOMBRE_EMPLEADO, ' ', E.APELLIDO_EMPLEADO) AS COLABORADOR,
    P.NOMBRE_PROFESION AS PROFESION,
    D.NOMBRE_DEPARTAMENTO AS DEPARTAMENTO,
    -- SELF-JOIN PARA TRAER EL NOMBRE DEL JEFE USANDO ID_JEFE -> ID_EMPLEADO
    CASE 
        WHEN E.ID_JEFE IS NULL THEN 'MÁXIMO RANGO / SIN JEFE DIRECTO'
        ELSE CONCAT(J.NOMBRE_EMPLEADO, ' ', J.APELLIDO_EMPLEADO)
    END AS JEFEDIRECTO
FROM EMPLEADO E
INNER JOIN PROFESION P ON E.ID_PROFESION = P.ID_PROFESION
INNER JOIN DEPARTAMENTO D ON E.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
LEFT JOIN EMPLEADO J ON E.ID_JEFE = J.ID_EMPLEADO; -- LEFT JOIN PORQUE EL DIRECTOR NO TIENE JEFE
GO

---------

-- (VW_RESUMENFINANCIEROCLIENTES)PERMITE ANALIZAR QUÉ CLIENTES GENERAN MAYOR FACTURACIÓN POR CONSULTORÍA.

CREATE VIEW VW_RESUMENFINANCIEROCLIENTES AS
SELECT 
    EC.ID_EMPRESA_CLIENTE AS ID,
    EC.CIF_EMPRESA AS CIF,
    EC.NOMBRE_EMPRESA AS CLIENTE,
    COUNT(DISTINCT P.ID_PROYECTO) AS CANTIDAD_PROYECTOS,
    ISNULL(SUM(DP.HORAS_TRABAJADAS), 0) AS TOTAL_HORAS_INVERTIDAS,
    CAST(ISNULL(SUM(DP.HORAS_TRABAJADAS * DP.COSTO_HORA), 0) AS DECIMAL(12,2)) AS TOTAL_INVERSION_REALIZADA
FROM EMPRESA_CLIENTE EC
LEFT JOIN PROYECTO P ON EC.ID_EMPRESA_CLIENTE = P.ID_EMPRESA_CLIENTE
LEFT JOIN DETALLE_PROYECTO DP ON P.ID_PROYECTO = DP.ID_PROYECTO
GROUP BY EC.ID_EMPRESA_CLIENTE, EC.CIF_EMPRESA, EC.NOMBRE_EMPRESA;

