USE DB_EMPRESA_SOFTWARE;
GO

----------------------------------------------
-- BUSCAR LA TARIFA VIGENTE E INYECTARLA EN EL COSTO DE LA HORA
-- PARA GARANTIZAR QUE EL PRECIO QUEDE CONGELADO ANTE FUTUROS CAMBIOS.
--------------------------------------------------------

IF OBJECT_ID('TRG_REGISTRAR_COSTO_HISTORICO_DETALLE', 'TR') IS NOT NULL
    DROP TRIGGER TRG_REGISTRAR_COSTO_HISTORICO_DETALLE;
GO

CREATE TRIGGER TRG_REGISTRAR_COSTO_HISTORICO_DETALLE
ON DETALLE_PROYECTO
AFTER INSERT
AS
BEGIN
    -- EVITA QUE EL TRIGGER DEVUELVA MENSAJES DE FILAS AFECTADAS PARA OPTIMIZAR EL RENDIMIENTO
    SET NOCOUNT ON;

    -- ACTUALIZAMOS EL COSTO_HORA DE LOS REGISTROS QUE SE ACABAN DE INSERTAR (TABLA INSERTED)
    UPDATE DP
    SET DP.COSTO_HORA = T.MONTO_HORA
    FROM DETALLE_PROYECTO DP
    INNER JOIN INSERTED I 
        ON DP.ID_DETALLE_PROYECTO = I.ID_DETALLE_PROYECTO
    INNER JOIN TARIFA T 
        ON I.ID_TARIFA = T.ID_TARIFA;
END;
GO


--------------------------------------------------
--IMPEDIR QUE SE REGISTREN HORAS NEGATIVAS O IGUALES A CERO.
-------------------------------------------

IF OBJECT_ID('TRG_VALIDAR_HORAS_TRABAJADAS', 'TR') IS NOT NULL
    DROP TRIGGER TRG_VALIDAR_HORAS_TRABAJADAS;
GO

CREATE TRIGGER TRG_VALIDAR_HORAS_TRABAJADAS
ON DETALLE_PROYECTO
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    -- VERIFICAR SI HAY REGISTROS CON HORAS NO VÁLIDAS
    IF EXISTS (SELECT 1 FROM INSERTED WHERE HORAS_TRABAJADAS <= 0)
    BEGIN
        -- LANZAR UN ERROR AL ESTILO T-SQL DE SQL SERVER
        THROW 50000, 'ERROR TRANSACCIONAL: LAS HORAS TRABAJADAS DEBEN SER MAYORES A CERO.', 1;
    END
END;
GO