USE DB_EMPRESA_SOFTWARE;
GO

---OPTIMIZACIÓN DE BÚSQUEDAS JERÁRQUICAS EN EMPLEADO MEJORA EL RENDIMIENTO DEL SELF-JOIN EN "VW_ORGANIGRAMAEMPLEADOS" 
-- AL BUSCAR RÁPIDAMENTE QUÉ EMPLEADOS TIENEN UN JEFE ESPECÍFICO.
-----------------

CREATE NONCLUSTERED INDEX IDX_EMPLEADO_JEFE
ON EMPLEADO (ID_JEFE)
INCLUDE (NOMBRE_EMPLEADO, APELLIDO_EMPLEADO);
GO


-- OPTIMIZACIÓN DE FILTRADO DE PROYECTOS POR ESTADO Y CLIENTES.
---------------------------------

CREATE NONCLUSTERED INDEX IDX_PROYECTO_CLIENTE_ESTADO
ON PROYECTO (ID_EMPRESA_CLIENTE, ID_ESTADO)
INCLUDE (NOMBRE_PROYECTO);
GO



-- 
-- ESTE ÍNDICE CUBRE COMPLETAMENTE LAS CONSULTAS DE SUMARIZACIÓN DE COSTOS.USA LA CLÁUSULA "INCLUDE" PARA ALMACENAR EN LAS HOJAS DEL ÍNDICE LAS HORAS
-- Y EL COSTO, EVITANDO HACER UN ACCESO COSTOSO A LA TABLA BASE.

CREATE NONCLUSTERED INDEX IDX_DETALLE_PROYECTO
ON DETALLE_PROYECTO (ID_PROYECTO, ID_EMPLEADO)
INCLUDE (HORAS_TRABAJADAS, COSTO_HORA);
GO